<?php

use WalkModifyXmlTree\XmlSnippetLoader;

$config = [];

//todo:与config/normal.php合并，是否可行？
//todo:若此配置文件为空，是否会产生错误？

//增加节点-----------------------------------------------------------------------

$snippet = new XmlSnippetLoader();
$section = $snippet->loadSnippet(__DIR__ . '/../Resources/snippet/education.xml');

$config[] = [
    'action' => 'addChildNode',
    'nodename' => 'SERVICE_MODULE',
    'path' => '*',
    'snippet' => $section,
];


//仅保留这些节点（及其子节点）------------------------------------------
$config[] = [
    'action' => 'keepOnlyTheseNodes',
    'nodePaths' => [
        'HEADER/CATALOG/LANGUAGE',
        'HEADER/CATALOG/CATALOG_ID',
        'HEADER/CATALOG/CATALOG_VERSION',
        'HEADER/SUPPLIER/SUPPLIER_ID',
        'HEADER/SUPPLIER/SUPPLIER_NAME',
        'HEADER/SUPPLIER/ADDRESS/NAME',
        'HEADER/SUPPLIER/ADDRESS/ZIP',
        'HEADER/SUPPLIER/ADDRESS/CITY',
        'HEADER/SUPPLIER/ADDRESS/COUNTRY',
        'HEADER/SUPPLIER/CONTACT/CONTACT_ROLE',
        'HEADER/SUPPLIER/CONTACT/FIRST_NAME',
        'HEADER/SUPPLIER/CONTACT/LAST_NAME',
        'HEADER/SUPPLIER/KEYWORD',
        'HEADER/SUPPLIER/EXTENDED_INFO/INSTITUTION_NUMBER',
        'NEW_CATALOG/SERVICE/PRODUCT_ID',
        'NEW_CATALOG/SERVICE/COURSE_TYPE',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/TITLE',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/DESCRIPTION_LONG',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/CONTACT_ROLE',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/LAST_NAME',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/ADDRESS/NAME',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/ADDRESS/ZIP',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/ADDRESS/CITY',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/ADDRESS/COUNTRY_CODED',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/ADDRESS/COUNTRY',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/CONTACT/ADDRESS/EMAILS/EMAIL',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_DATE/START_DATE',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_DATE/END_DATE',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/COURSE_ID',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/EXTENDED_INFO/INSTITUTION',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/EXTENDED_INFO/INSTRUCTION_FORM',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/EXTENDED_INFO/EDUCATION_TYPE',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/LOCATION/NAME',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/LOCATION/ZIP',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/LOCATION/CITY',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/LOCATION/COUNTRY_CODED',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/LOCATION/COUNTRY',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/DURATION',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/FLEXIBLE_START',
        'NEW_CATALOG/SERVICE/SERVICE_DETAILS/SERVICE_MODULE/EDUCATION/MODULE_COURSE/EXTENDED_INFO/SEGMENT_TYPE',
    ]
];

//删除节点-----------------------------------------------------------------------

/*$config[] = [
    'action' => 'removeNode',
    'nodename' => 'STUDY_COURSE',
    'path' => 'NEW_CATALOG/SERVICE/SERVICE_DETAILS',
];*/


return $config;
